# Generated by Django 5.1.5 on 2025-01-19 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_contact_user_profile_bio_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='post',
        ),
    ]
