# Generated by Django 5.1.5 on 2025-01-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_follow_delete_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, to='myapp.profile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.CharField(blank=True, default='2025/01/20', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.CharField(blank=True, default='2025/01/20', max_length=100),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
